# Generated by Django 3.2.9 on 2021-11-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'ordering': ['-created_at']},
        ),
    ]
